### ISSUE TITLE
Filter out split geometries with too few buildings

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm-splitter#28]
**Describe the bug**

- The splitting algorithm may produce a random split geometry that contains no features (see the tiny blue polygon):

![image](https://github.com/hotosm/fmtm-splitter/assets/78538841/1ebc69ff-feee-4f88-a1cc-32cb177e2afb)

- This shouldn't happen often, but is possible.
- In order to avoid, we should filter out any final polygons that have areas smaller than a certain size, perhaps 10m2?

**To Reproduce**

- AOI GeoJSON:

```json
{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"coordinates":[[[85.29998911024427,27.714008043780694],[85.29998911024427,27.710892349952076],[85.30478315714117,27.710892349952076],[85.30478315714117,27.714008043780694],[85.29998911024427,27.714008043780694]]],"type":"Polygon"}}]}
```

- Data extract attached as a .txt file to get around upload restrictions. Rename to .geojson:

[kathmandu_extract.txt](https://github.com/hotosm/fmtm-splitter/files/14982742/kathmandu_extract.txt)

- Use the splitting algorithm set to 100 buildings average.

**Expected behavior**

- Geometries like that are clearly an artifact that should be removed.

**Comment by spwoodcock** [comment]
This should be fixed by https://github.com/hotosm/fmtm-splitter/pull/53

If we need an actual threshhold param, we can revisit this if needed.

**Comment by Sujanadh** [comment]
Actually I think we don't care about area if it has sufficient features in it ( for example each task with around 40 features lets say if user wants to split by  `num_buildings=40`), so we need to determine threshold based on the number of features per task maybe `(-0.5x to .05x => 20-40-60 not less than 20 or not greater than 60)`
