### ISSUE TITLE
Creating task areas with no features should not be possible

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm-splitter#37]
**Describe the bug**

- This is specific to the **split by square** algorithm.
- It's possible that sometimes a task area is generated with no features inside it.
- This happens when an AOI is not square.

**To Reproduce**

Project https://fmtm.hotosm.org/project/100

**Expected behavior**

- The task areas with no features are deleted at the end of the `split_by_square` function to avoid this problem.

**Screenshots**

You can see two small task areas that have no buildings:
![image](https://github.com/hotosm/fmtm-splitter/assets/78538841/6968392e-4dc3-4cc5-b52a-e1cdf22f8be5)

**Additional considerations**

I imagine this problem does not exist on the complex splitting algorithm, as we handle the case already.

**Comment by Sujanadh** [comment]
We do not pass data extracts to splitbysquare in order to check if the resulting polygons contain features or not. 
Options:
- Update the logic to check if the resulted tasks contains features or not in splitbysquare by passing data extracts.
- get the splitted tasks in fmtm and update there if the task contains features or not; if some tasks donot have features, delete them or merge them.

**Comment by manjitapandey** [comment]
Is the problem here only specific to features not available because the task area is small or does it implemented on tasks with more area too where there is no features. Cases could be of forest areas?

**Comment by Sujanadh** [comment]
I have made some improvements to this issue:
- updated the splitbysquare to include data extracts
- considering square polygons where atleast a data extract feature is present.

Output:
Before :
![image](https://github.com/hotosm/fmtm-splitter/assets/109404840/b13c70f8-b2b3-47a2-aebd-b521d477db06)

After:
![Screenshot from 2024-07-09 13-47-48](https://github.com/hotosm/fmtm-splitter/assets/109404840/b17084d9-dfb2-42b8-8864-5b1953dbbc55)

AOI geojson: 
[durbar_poly.txt](https://github.com/user-attachments/files/16140217/durbar_poly.txt)
data extracts:
[durbar_exports.txt](https://github.com/user-attachments/files/16140221/durbar_exports.txt)

**Comment by spwoodcock** [comment]
Possibly this one?

https://fmtm.hotosm.org/project/104
