### ISSUE TITLE
Use underpass to get the data for the AOI

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm-splitter#4]
Right now the data source is hardcoded to be a local postgres that already has the data in it. It should be possible to also download the data within the AOI from Underpass, and that will bootstrap the local database.

**Comment by spwoodcock** [comment]
For the tests in https://github.com/hotosm/fmtm-splitter/pull/14 I added a param to pass a data extract geojson.

Do you think we should:
- Ask users to use osm-rawdata, get a geojson, then pass to fmtm-splitter.
- Or include osm-rawdata in this repo and handle the data extract download internally.
?

**Comment by spwoodcock** [comment]
Added in https://github.com/hotosm/fmtm-splitter/commit/b0c56407b108c1d3327695d9c919d4e7b08c134d
