### ISSUE TITLE
Display the task polygons for developers

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm-splitter#5]
It'd be useful when working on the SQL queries to display the output of the generated tasks in a window on the desktop. This would save time loading the output file into an external editor. This could be done using matplotlib or geopandas. 

An enhanced version of course would let you edit and resubmit the query and test it, but that'll be an other issue.

**Comment by spwoodcock** [comment]
Closing in favour of https://github.com/hotosm/fmtm-splitter/issues/66
