### ISSUE TITLE
fmtm-splitter shouldn't require being online

### ISSUE THREAD

**Issue by rsavoye** [hotosm/fmtm-splitter#50]
When splitting a polygon into tasks, a data extract shouldn't be required Currently if you only want the multipolygon of the tasks, it downloads a data extract, even though one isn't desired. Most other projects using fmtm-splitter (or whatever if may get renamed to) don't need the data extract. 

For example: fmtm-splitter -v -b Boundaries/DixieNationalForest.geojson -m 10000, shouldn't download data, it should just split the boundary multipolygon into squares.

**Comment by spwoodcock** [comment]
This is solved in latest: https://github.com/hotosm/fmtm-splitter/blob/23d3a61bb182b4558dddeae79dc9b8eda4cc40ca/fmtm_splitter/splitter.py#L196
