### ISSUE TITLE
Small polygons with no features inside the regular splitted polygons

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm-splitter#51]
**Describe the bug**
In some cases of splitting task using task splitting algorithm, the regular splitted polygon contains small polygons with no features inside. 

**To Reproduce**

1. Go to 'fmtm'
2. Click on 'create project'
3. Apply task splitting algorithm.

**Expected behavior**
In case there is any polygon or line or point which are counted as a task exist inside the polygon, that should be removed. 

**Screenshots**
![image](https://github.com/user-attachments/assets/6b9e0a18-3ef5-4195-9d84-ca059584638e)

**Comment by spwoodcock** [comment]
Dup of https://github.com/hotosm/fmtm-splitter/issues/28

**Comment by Sujanadh** [comment]
I don't think its duplicate, #28 is related to smaller tasks with few numbers of features or without features. My PR only fixes those small tasks which donot have any features in it(considered as holes). I will be working on this issue onward.
